name: flite_generator
description: "Generator for the `flite` package"
version: 1.0.0
repository: https://github.com/sudoadarsh/Flite

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flite: ^1.0.0
  analyzer: ^6.7.0
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter: